name = "refine-sqlite-worker"
main = "src/worker.js"
compatibility_date = "2024-08-15"

[env.production.vars]
# Environment variables for production

[env.development.vars]
# Environment variables for development

[[env.production.d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "refine-sqlite-db"
database_id = ""

[[env.development.d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "refine-sqlite-db"
database_id = ""
