name: Comprehensive CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  test-bun:
    name: Test with Bun (SQLite Native)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies with Bun
        run: bun install
      
      - name: Install workspace dependencies
        run: bun install --workspaces
      
      - name: Check Bun version and SQLite support
        run: |
          bun --version
          echo "Bun version: $(bun --version)"
          echo "Testing Bun SQLite support..."
          bun -e "console.log('Bun SQLite native support available')"
          
      - name: Clean up previous test databases
        run: |
          rm -f test-*.db
          rm -f *.test.db
          rm -f test-nodejs.db
          echo "Cleaned up test databases"
      
      - name: Run tests (refine-sql) with Bun
        run: bun run test:bun
      
      - name: Run tests (all workspaces) with Bun
        run: bun run test:bun
      
      - name: Build refine-sql with Bun
        run: bun run build
        
      - name: Build all packages with Bun
        run: bun run build:all
        
      - name: Test build output
        run: |
          ls -la dist/
          echo "Build artifacts created successfully"

  test-node-fallback:
    name: Test with Node.js (Fallback)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install workspace dependencies
        run: npm install --workspaces
      
      - name: Clean up previous test databases
        run: |
          rm -f test-*.db
          rm -f *.test.db
          rm -f test-nodejs.db
      
      - name: Run tests with Node.js (Mock mode)
        run: npm run test:run
        env:
          CI: "true"
          FORCE_MOCK_SQLITE: "true"

  test-with-coverage:
    name: Test with Coverage (Bun)
    runs-on: ubuntu-latest
    needs: test-bun
    if: github.event_name == 'pull_request'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies with Bun
        run: bun install
      
      - name: Install workspace dependencies
        run: bun install --workspaces
      
      - name: Clean up previous test databases
        run: |
          rm -f test-*.db
          rm -f *.test.db
          rm -f test-nodejs.db
      
      - name: Run tests with coverage (Bun)
        run: bun run test:coverage

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: test-bun
    if: github.event_name == 'release'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Install workspace dependencies
        run: npm install --workspaces
      
      - name: Build all packages
        run: npm run build:all
      
      - name: Publish refine-sql
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Publish refine-orm
        run: npm publish --workspace=packages/refine-orm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
